openapi: 3.0.1

info:
  title: Product API
  description: |
    Product API sözleşmeleri bulunduran yml dosyası.

    Bu dosyadaki kalıplar product-service içerisinde kullanılmak zorundadır.
    Bu kalıpların dışına çıkılamaz.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Development Server
  - url: https://api.turkcell.com.tr
    description: Production Server